   <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a> <br>
                    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
                </div>
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : '') ?>
                    <form action="<?php echo BASE; ?>/cadastro/cadastrar/" class="form-horizontal" method="post">
                        <div class="form-group">
                            <label for="name" class="col-sm-3 control-label">Nome:</label>
                            <div class="col-sm-8">
                                <input required type="text" class="form-control" name="name" id="name" placeholder="Nome Completo" value="<?php echo $this->request->post('name') ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-sm-3 control-label">Email:</label>
                            <div class="col-sm-8">
                                <input required type="email" class="form-control" name="email" id="email" placeholder="seuemail@site.com.br" value="<?php echo $this->request->post('email') ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="username" class="col-sm-3 control-label">Usuário:</label>
                            <div class="col-sm-8">
                                <input required type="text" class="form-control" name="username" id="username" placeholder="Nome de usuário" value="<?php echo $this->request->post('username') ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Senha:</label>
                            <div class="col-sm-8">
                                <input required type="password" class="form-control" name="password" id="password" placeholder="Sua senha">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">Cadastrar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
