   <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a> <br>
                    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
                </div>
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : '') ?>
                    <form action="<?php echo BASE; ?>redefinir/alterar-senha/" class="form-horizontal" method="post">
                        <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Nova Senha:</label>
                            <div class="col-sm-8">
                                <input type="password" class="form-control" name="password" id="password" placeholder="Nova senha">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">Alterar Senha</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
