                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : '') ?>
                    <form action="<?php echo BASE; ?>recuperar/alterar-senha/<?php echo $view_token; ?>" class="form-horizontal" method="post">
                        <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Nova Senha:</label>
                            <div class="col-sm-8">
                                <input type="password" class="form-control" name="password" id="password" placeholder="Nova senha">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">Alterar Senha</button>
                            </div>
                        </div>
                    </form>
                </div>
