                <div class="panel-body">
                    <?php 
                        echo (isset($this->menu) ? $this->menu : ''); 
                        $this->partial('message', array(
                            'msg' => 'Uhull! Você foi autenticado com sucesso!'
                        )); 
                    ?>
                    <p>
                        Olá <?php echo $view_user->name; ?>, seja bem vindo(a)!
                    </p>
                    <p>
                        <a href="<?php echo BASE; ?>/login/sair" class="btn btn-danger">Sair</a>
                    </p>
                </div>