                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : '') ?>
                    <form action="<?php echo BASE; ?>login/logar/" class="form-horizontal" method="post">
                        <div class="form-group">
                            <label for="username" class="col-sm-3 control-label">Usuário:</label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="username" id="username" placeholder="Nome de usuário" value="<?php echo $this->request->post('email') ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">Senha:</label>
                            <div class="col-sm-8">
                                <input type="password" class="form-control" name="password" id="password" placeholder="Sua senha">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                </div>

